language: ruby
sudo: false

cache: bundler

before_install:
  - 'gem update bundler'

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - TEST_SUITE=rspec
    - TEST_SUITE=rubocop

script:
  - 'bundle exec rake donut:travis:$TEST_SUITE'

jdk:
  - oraclejdk8

rvm:
  - 2.4.1
