language: ruby
sudo: false

cache: bundler

services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libclamav6 libclamav-dev clamav clamav-data
  - 'gem update --system'
  - 'gem update bundler'

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - TEST_SUITE=rspec
    - TEST_SUITE=rubocop

script:
  - 'bundle exec rake donut:ci:$TEST_SUITE'

jdk:
  - oraclejdk8

rvm:
  - 2.4.1
#  - 2.5
