terms:
    - id: /authorities/search/loc/subjects
      term: LCSH
      active: true
    - id: /authorities/search/assign_fast/all
      term: FAST
      active: true
    - id: /authorities/search/geonames
      term: GEONAMES
      active: true
