default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 5
  username: docker
  password: d0ck3r

development:
  <<: *default
  pool: 1000
  port: 5433
  timeout: 5000
  database: donut_dev

test:
  <<: *default
  port: <%= Rails.env.development? ? 5433 : 5434 %>
  database: donut_test

production:
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: db/production.sqlite3
