common_indexer:
  allowed_keys:
    - admin_set
    - collection
    - title
    - date
    - permalink
solr:
  configset: donut
  configset_source_path: <%= File.join(Rails.root, 'solr', 'conf') %>
  collection_options:
    async:
    auto_add_replicas:
    collection:
      config_name: donut
    create_node_set:
    max_shards_per_node:
    num_shards: 1
    replication_factor:
    router:
      name:
      field:
    rule:
    shards:
    snitch:
zookeeper:
  connection_str: "localhost:9983/configs"
geonames_username: ''
fits: {}
active_job: {}
aws:
  buckets: {}
  queues: {}
ffmpeg: {}
system_user: 'repository@northwestern.edu'
ark: {}