localstack:
  sqs: false
  port_offset: 100
aws:
  buckets:
    uploads: dev-uploads
    batch: dev-batch
  queues:
    ingest: donut.fifo
iiif:
  endpoint: http://localhost:8183/iiif/2/
common_indexer:
  endpoint: http://localhost:9201/
  allowed_keys:
    - title
