derivatives_path: <%= File.join(ENV['HOME'], '.nuldata', 'derivatives') %>
localstack:
  sqs: false
  port_offset: 100
aws:
  endpoint: https://devbox.library.northwestern.edu:9001/
  buckets:
    batch: dev-batch
    dropbox: dev-dropbox
    fedora: dev-fedora-binaries
    manifests: dev-manifests
    pyramids: dev-pyramids
    uploads: dev-uploads
  lambdas:
    pyramid: dev-create-pyramid-tiffs
  queues:
    ingest: donut.fifo
iiif:
  endpoint: http://localhost:8183/iiif/2/
metadata:
  endpoint: https://devbox.library.northwestern.edu:3000/
common_indexer:
  endpoint: http://localhost:9201/
solrcloud: true
