localstack:
  sqs: true
  port_offset: 100
active_job_queue:
  url: http://localhost:4576/queue/donut
aws:
  buckets:
    uploads: dev-uploads
    batch: dev-batch
iiif:
  endpoint: http://localhost:8183/iiif/2/
