aws:
  endpoint: http://127.0.0.1:9000
  region: us-east-1
  aws_access_key_id: minio-dev-key
  aws_secret_key_id: minio-dev-secret
  buckets:
    uploads: dev-uploads
    batch: dev-batch
iiif:
  endpoint: http://localhost:8182/iiif/2/
