derivatives_path: <%= File.join(ENV['HOME'], '.nuldata', 'derivatives') %>
localstack:
  sqs: false
  port_offset: 200
aws:
  endpoint: http://localhost:9002
  buckets:
    batch: test-batch
    uploads: test-uploads
    manifests: test-manifests
    export: test-export
common_indexer:
  endpoint: http://localhost:9202/
iiif:
  endpoint: http://localhost:8183/iiif/2/
metadata:
  endpoint: http://localhost:9002/test-manifests/
solrcloud: true
zookeeper:
  connection_str: "localhost:9985/configs"
aws_region: us-east-1
nul_collection_type: gid://nextgen/hyrax-collectiontype/1
nusso:
  consumer_key: test-key
