derivatives_path: <%= File.join(ENV['HOME'], '.nuldata', 'derivatives') %>
localstack:
  sqs: false
  port_offset: 200
aws:
  endpoint: http://localhost:9002
  buckets:
    batch:   test-batch
    uploads: test-uploads
    manifests: test-manifests
common_indexer:
  endpoint: http://localhost:9202/
metadata:
  endpoint: http://localhost:9002/test-manifests/
solrcloud: true
zookeeper:
  connection_str: "localhost:9985/configs"
