# Generated by hyrax:models
class Collection < ActiveFedora::Base
  include ::Hyrax::CollectionBehavior
  # You can replace these metadata if they're not suitable
  include Hyrax::BasicMetadata
  include MicroserviceMinter
  include ::CommonIndexer::Base

  self.indexer = Donut::CollectionIndexer

  def to_common_index
    CommonIndexService.index(self)
  end
end
