# Generated by hyrax:models:install
class FileSet < ActiveFedora::Base
  include ::Hyrax::FileSetBehavior
  # include ::Schemas::Technical::Exif
  include MicroserviceMinter

  # apply_schema Schemas::Technical::Exif
end
