# Generated by hyrax:models:install
class FileSet < ActiveFedora::Base
  property :area_of_interest, predicate: ::RDF::Vocab::EXIF.subjectLocation, multiple: false

  include ::Hyrax::FileSetBehavior
  include MicroserviceMinter
  include ::CommonIndexer::Base

  def to_common_index
    CommonIndexService.index(self)
  end
end
